# Generated by Django 4.2.1 on 2023-08-04 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_alter_category_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=250, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("Description", models.TextField(blank=True)),
                ("Image", models.ImageField(blank=True, upload_to="Products")),
                ("Price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("stock", models.IntegerField()),
                ("available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ("Name",),
            },
        ),
    ]
